### ISSUE TITLE
Some comments after a static review of the code/design.

### ISSUE THREAD

**Issue by parenthetical-e** [voytekresearch/fooof#53] opened 2017-12-12 18:37 UTC
FOOOF notes

1. Variable/kwarg naming is inconsistent in style. Sometimes verbose names are used (’bandwidth_limits’) other times highly abbr. var. nm. are used (‘bg_use_knee’). Same holds true for FOOOF.atttr_ names, etc. I’d opt for a more verbose style.
2. I appreciate the intended convenience of FOOOF.model() but it’s auto-plot functionality has has two negative effects. a. It may lead to confusion: ‘model’ seems like a top-level generic command. It’s the first thing I would try if approaching the library cold. The user may however be running on a remote connection, where auto-plotting can be both unexpected and SLOW as the plot is sent over SSH/X11. That is, the name ’model’ seems like the generic top-level way to invoke FOOOF, but it is not. b. It adds a hard unnecessary dependency of FOOOF on matplotlib. Consider renaming to ‘report’?  I realize you address this in the examples; I don’t that is good enough.
3. The methods do not in `plt` do not test for a matplotlib install. This will lead to not-graceful failures. Wrap the matplotlib import in a try/except and flag failure to import throughout the package so things go smoothly?
4. The fit.FOOOF class has code intended for group.FOOOF (e.g., https://github.com/voytekresearch/fooof/blob/master/fooof/fit.py#L278). This is a pretty serious abstraction leak, even if it is ‘private’. Is this really the best solution?
5. It seems odd/inconsistent to generate a ‘FOOOFResult’ on request but not use that internally on FOOOF itself. What’s the use case here? Why use a named tuple instead of collecting/returning the key attrs_ as they are? …There should be one right way to do things.
6. While I really like the reporting-as-text-thing (‘print_results’) it uses a lot of whitespace. The report could be made more compact/succinct. If printing several results on the CL, the info density would be very low; there’d be more scrolling than necessary, which is a pain in some terminal environments, and even in the notebook.
7. What is the intended use case for being able to load past FOOFs back into FOOOF - `https://github.com/voytekresearch/fooof/blob/master/fooof/fit.py#L365`.  Who would do this? When? Why? 
8. Docs on private attrs (https://github.com/voytekresearch/fooof/blob/master/fooof/fit.py#L66). If they are for users, remove the leading ‘_’. If they are private, don’t doc them in the top-level docs?  These are very useful to debug, but they are only useful if you know FOOOF internals. What level of competency do you expect from users?
9. Overall comment about 7/8: it is tempting to want to add things, “that might be nice to have” or “someone might want” but that comes with a real burden on maintenance and code complexity. I’d make sure the features/info you expose cover only the core expected uses and then let people’s actual use determine other additions. Maybe all that has passed that test; I don’t know. Just sayin’ :)
10. In FOOF (note the lack of one ‘O’) I had a notebook that the stepped through all the internal processing steps, showing intermediate results. Might be good to do the same for FOOOF.

(I'm going to do some runtime/performance analysis later as well...)

**Comment by parenthetical-e** [comment] 2017-12-12 18:40
Wait I should say something nice: you folks did a great job! 

I. proud.

**Comment by parenthetical-e** [comment] 2017-12-12 18:41
Also, if any of my Qs have been answered in previous thread/issues/whatever do point me at that, with my apologies. :)

**Comment by TomDonoghue** [comment] 2017-12-12 19:08
This is awesome, exactly the kind of code-review I was looking for, thanks @parenthetical-e !

All very good points, I will update / respond as I go through the clean-up round of the code-base over the next day or two.

**Comment by TomDonoghue** [comment] 2017-12-15 04:19
Okay: bunch of comments, follow-ups etc. I tried to sign post where things are at for each point. 
@voytek @rdgao : Your thoughts on some of the open questions would be great.

Where things are mentioned to be 'done', they are in PR #55 

1) Request Input.
	- Hmmm. Yeah, I see what you mean. So, in my mind it was all pretty verbose, but I guess really the current approach is more like 'pretty verbose, but limiting to still max length of ~ 15 characters', creating an inconsistent use of abbreviations. Perhaps the most common deviation from being really verbose is using 'bg' in place of 'background'.
	- So, what should we change? I don't really like 'bg_use_knee' to start with. Move to 'background_use_knee'? Something else? What other public params / attributes might do well with changing? Nows the best time?
	- Related: I vote for changing 'max_n_oscs' -> 'max_n_gauss', since I think it's clearer to not overly conflate gaussians with distinct oscillations (because FOOOF has a tendency to use overlapping gaussians to fit what we would probably consider 1 oscillation). Thoughts?
	- ^Y'alls thoughts here would be helpful, I think I'm in too deep / too used to it as is, to notice weirdness. 
2) Request Input. 
	- I agree. I think 'report' is better, but is it clear that report should take in data and run the model, as opposed to just reporting? What about 'fit_n_report'?
	- Or, we could drop the 'all in one', and have 'fit' (as is), 'report' (new: displays print_results & plots). 
	- Either way, we should perhaps change 'create_report' -> 'save_report', as I think it's not currently obvious that 'create_report' saves, but doesn't return / display anything. 
3) Agreed. 
	- Not yet done (I need to check into how to do so), but yes, I agree on making mpl an optional dependency, and will do that. 
4) Done. 
	- Yep, this was a messy hack-fix. Updated to fix abstraction-leak.
5) Question / Request Input.
	- Hmm. This is something I pulled from scipy.stats.....
	- I'm not sure I quite understand the point, as it seems to me this does collect & return the key attrs as they are (at the moment you ask for results). Within FOOOF, this is basically just a mild convenience of bundling outputs, with labels, but becomes more important (I think) for collecting organized data in FOOOFGroup. I guess an alternative would be, in FOOOFGroup, to make all the results attributes into matrices all collect as it runs (similar to how FOOOFGroup has 'psds'), but the issue is quirky sizes: there's not an obvious clean way to stack oscillation outputs, of various sizes. 
	- So: I'm not sure I'm clear on why this is disprefered, and/or I'm not sure how to cleanly get rid of it - but if you have a suggestion of how to do so I'd be interested. 
6) Question / Request Input. 
	- Yes, this might be over-tuned to using  notebooks. My (not great) rebuttal, is:
		- Making it more succint (removing extra lines, perhaps right justified) might make it harder to read (and less nice looking)
		- My expectation of the use case of these method is quick checking, not looking at any large number of them. 
		- On my MacOS terminal, the prints do look fine / tractable.
		- My (could be wrong) guess is that notebook use of these methods will be more than terminal use, and so I'm okay with somewhat over-tuning to notebooks. 
	- That said: I'm happy to be over-ruled on this, if others have votes on way or another. 
7) Comment / Request Input. 
	- I think this is actually fairly key (most users will / should use this), for several reasons / use cases: 
		- This method can load a settings file, which is useful to ensure consistency by using and loading a settings config file. 
		- Easy support for separating running FOOOF, from analyzing results. You set FOOOF up, run a bunch of data, saving as you go. Now, after, with load:
			- Easy checking of past-runs of model. You check the reports, some group / results are weird. Load, plot, explore what's happening. 
			- Organized loading of FOOOF data for further analysis. You can load back into a FOOOF object, which keeps thing organized, and then use the object to support selecting data etc (ex. get_all_data) to then do whatever you want to do. The alternative is requiring users to do more low-level work loading loading and parsing the JSON files (or a bigger re-vamp of our IO, in one way or another, but from prior discussion here (#40 ), I didn't get a sense of preferable alternatives). 
	- Conclusion: I'm open to replies / comments / suggestions, but my vote is keep / leave as is. 
8) Done / Comment
	- Yep, I agree, this is a good point, and I don't want/expect users to have to care / think about them. I do want to keep them documented somewhere, so they are available for any users who do want to jump into the actual code. I've moved them to the documentation at the top of the file. Not sure if this is the best spot (is there some canonical location for private docs like this?). If anyone has suggestions of where to put em, let me know. 
9) Comment / Request Input
	- I totally agree. Definitely something on my mind. I'm wary that I reckon I have a tendency to over-add, and that by largely tuning to myself as a user, I'm tuning to the least representative user. This might argue against, for example, having (or further adding to) fooof.analysis.
	- However, I do think I could argue, that all that is in here is pretty key. Part of my logic (related to 7 too), is that we should ourselves offer any functionality that otherwise a majority of users would likely have to often re-write (idiosyncratically) themselves, and in doing so, I've chosen a degree of adding things / trying to be friendly to the user (adding FOOOFGroup, IO, analysis, etc), over a what could otherwise have been design choice with a stronger inclination of being lean and concise. Another benefit is we get more input on the 'right' way to do things (standardizing saved outputs, for example, making sharing way easier). 
	- Conclusion: I'm open to replies / comments and especially any particular suggestions of anything to hide / remove, or freeze further development off, but I think I stand by all that is currently in / exposed. 
10) Done. 
	- Yes, great idea! Added to tutorial materials. In PR #54

**Comment by TomDonoghue** [comment] 2017-12-15 10:41
Okay: so I've opened a round of PRs now (tutorials, last_tweaks, and release). 

Other than anything that comes up in those PRs, this Issue is the last thing to do before it should be ready to tag and release - I'm done all my updates.

**Comment by rdgao** [comment] 2017-12-15 17:11
I don't know what the conventions are for any of these in proper software engineering, so I'm just putting in my two cents as a naive user. It's just one set of opinions.

1. bg seems like a fine shortform for background, if it's consistently used elsewhere. I'm ambivalent about this, and prefer shorter args just to keep the code short. fit_bg_knee?

I would definitely vote for using max_n_gauss, though, because that's what it spits out, not definitive oscillations. It will take a bit of explaining the difference between gaussian and oscillation, i.e. the overlap problem, but it's a more much accurate portrayal of the algorithm.

2. Again, pretty ambivalent, but I like the all-in-one reporting, because I'm lazy. Maybe change the name to make it sound less prominent, like Erik said, but I would vote to keep this "one button and it works" functionality.

6. I would definitely like to keep this. The reporting/printout functionalities are probably my favorite things here because it got me onboard with using the thing right away. I have an aversion now to software that seems pretty easy to use in the tutorial, but every line seems to break when you try it on your own data. The report explains very clearly what the outputs are and the plotting lets me see right away if the fits look about right, and whether I've put in the right PSD. It's a great noob-friendly feature, and once one becomes a proficient user, they don't have to interact with this at all.

7. I haven't used this yet, but I think it's nice to have for reproducibility purposes. I don't know if you're still saving the PSDs as a part of that output, and that could be space/time consuming, but I would definitely like to save the configurations I've used, FieldTrip style, instead of going back to old notebooks to dig them up.

**Comment by voytek** [comment] 2017-12-16 19:31
My thoughts:

1. Verbosity is preferred when it doesn't impair readability, and when less verbose options are non-obvious. fit_background_power_spectral_density_knees is, for example, too verbose, whereas fit_bg_psd_knee is fine, and obvious given the context of the code itself, for example.

2. No strong opinions here, honestly.

3. I agree with Gao: these are very useful things to help onboard new users, but also agree having mpl as a required dependency is unnecessary for power users. Can “easily” create a lean fooof that power users can run that don’t require mpl, but I believe the core fooof should require it because it’s so damned useful to be able to see what it’s doing and how it works.

4. Fix leaks!

5. Again no opinion here, but largely because I’ve not played with this latest version enough.

6. Strongly agree that the reporting can and should be more compact, with far less whitespace.

7. Yeah, when running large batches of data it’s nice to be able to pop back to explore strange fits.

8. I think Tom’s solution here is good.

9. no comments needed

10. Strongly agree here, and I think Tom’s new tutorials look great.

**Comment by parenthetical-e** [comment] 2017-12-17 02:16
1. What I was trying to get at a deeper complexity/inconsistency. I’m going to try to explain using examples.I made it so during invocation there are two key terms/ideas for the user to keep track of as they configure FOOOF: ’peaks’ and ‘background’. 

bandwidth_limits -> peak_width_range
max_n_gauss     -> max_n_peaks
min_amp             -> min_peak_amplitude
amp_std_thresh  -> min_peak_std  # (I don’t understand what this does)
bg_use_knee      -> background_mode = {‘knee’, ’fixed’)  # not boolean
verbose               -> be_like_erik

freqs_                  ->  freqs_
freq_range_         ->  drop? (redundant with freqs_ ?)
freq_res               ->  drop? (redundant with freqs_ ?)

Technically you  could foof raw fft; density is not needed. Plus why not be explicit?
psd_                                ->  power_spectrum_

# we have a ridiculous name,,, own it :)
psd_fit                             -> foofed_psd_  

background_params_     ->  background_params_
peak_params_                ->  peak_params_

# A little more explicit/consistent
r2_  				      ->  r2_error_
error_                              ->  rmse_error_  (Is that what this is?) 

2. I think `report` is fine. They have to look at the signature to call anyway.
3. Cool
4. Cool.
5. If you need it internally use it internally, OK, that’s not what I’m worried about. I don’t like *exposing* it because you are mixing type systems. 

The primary type of FOOF before this is an instance of a class. So if I got a ‘result’ object back I’d expect it to an instance of class (e.g, a FOOFResults class) not a `namedtuple` which are very much  different beasts, akin to structs than class instances. 

Note: I like that ‘namedtuples’ are gaining popularity, and when can be used with the coming (?) mypy-like optional typing scheme, they’ll be an interesting functional (yaaay!) alternative to classes (boooo!). We are not there yet; the language is not even close to there yet.

6. Agreeing with Brad’s agreement. I’ll mockup a counter-offer, :)

7. Keep it. But! I’ll bet y’all a burrito each this sees very little use outside the lab. 
8. Cool
9. Cool.
10. Yay!

**Comment by voytek** [comment] 2017-12-17 19:10
> We have a ridiculous name... own it :)
> psd_fit -> foofed_psd_

Totally.

> Keep it. But! I’ll bet y’all a burrito each this sees very little use outside the lab.

You may very well be right, but @TomDonoghue's running literally millions of FOOOFs, so even if we're the only ones using it, we'll be using it a lot. This is a case where I'm happy to prioritize our needs over optimizing for some more general ideal.

**Comment by TomDonoghue** [comment] 2017-12-20 05:42
Okay, so after the round of comments, it seems 2-10 are pretty much settled, with a couple changes pushed to actual_last_tweaks:
- (2) change 'model' -> 'report'
- (3) mpl is now an optional dependency, and updated to be able to run smoothly without it available, fail informatively if you try to use functionality that requires it, and skip tests if running without mpl (@parenthetical-e if you want to eyeball how I did this: I think it makes sense, but I wasn't 100% sure of the best way to do it). 
- (5) FOOOFResult: I guess I'm less worried than you are about 'mixing types'. Or, it's more that I don't have an action item here. Although it's easy not to return a FOOOFResult in FOOOF, for Group, it's not clear how to organize without them (they could be pushed more internal, but you would probably still sometimes have/want to deal with them). So, I don't know how to change, if you (or anyone) has suggestions, happy to try that, but as is, I'm going to leave as is for now. 
- (6) Concise printing: so, as something of a compromise, it now has an easy toggle between old-school (whitespacey), and a new concise version (good for terminal, etc). The duality is largely because the generated strings are recycled into the reports, and I don't think we want to squish them, and it keeps the more aesthetic printing available for notebooks. Currently, as defaults, calling string methods directly uses concise, where as reports are 'non-concise', but it's also exposed for users to choose. Check it out, and let me know if this fixes it in a way you're all happy with. (I like this solution, although I'm not sure about the best defaults, because it's also perhaps non-intuitive that calling print_results isn't quite the same representation as the reports).

**Comment by parenthetical-e** [comment] 2017-12-20 06:28
Okay dokay!


(e)

**Comment by TomDonoghue** [comment] 2017-12-20 15:35
I am going to open a new issue to discuss a proposed API overhaul. 

Otherwise does everything here look good? If so, I will merge the 'last_tweaks_...' PR and re-branch for the API.

**Comment by parenthetical-e** [comment] 2017-12-20 16:32
Go for it.

**Comment by TomDonoghue** [comment] 2017-12-23 18:33
@parenthetical-e : if you did/do any runtime/performance analysis, open a new issue for that. 

Otherwise, this all seems covered, so I'm going to close this. 

Thanks again for the in-depth comments!

**Closed by TomDonoghue** 2017-12-23 18:33 UTC
